# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/milletlte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/milletlte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/milletlte/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/milletlte/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/samsung/milletlte/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/milletlte/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/milletlte/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/milletlte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/milletlte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/milletlte/proprietary/lib/hw/vibrator.default.so:lib/hw/vibrator.default.so \
    vendor/samsung/milletlte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/milletlte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/milletlte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/milletlte/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so
